# -*- coding: utf-8 -*-
"""Carcinoma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AEhS2_EF9CPQPRswKJetIVBbJyb1q4mD
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('./drive/My Drive/Practice/cancer_classification.csv')
 df.head().transpose()

sns.countplot(x='benign_0__mal_1',data=df)

df.corr()['benign_0__mal_1'][:-1].sort_values().plot(kind='bar')

sns.heatmap(df.corr())

X = df.drop('benign_0__mal_1' , axis=1).values
y = df['benign_0__mal_1'].values

from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=101)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

